# The overall format is standard TOML format, v0.5.0.
# Find more information on toml format here:  https://github.com/toml-lang/toml
# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[43,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
# The license for you mod. This is mandatory metadata and allows for easier comprehension of your redistributive properties.
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license="All rights reserved"
# A URL to refer people to when problems occur with this mod
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/"
[[mods]] #mandatory
modId="aelven_expansion" #mandatory
# ${file.jarVersion} will substitute the value of the Implementation-Version as read from the mod's JAR file metadata
# see the associated build.gradle script for how to populate this completely automatically during a build
version="${file.jarVersion}" #mandatory
displayName="Aelven Expansion" #mandatory
# A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
#updateJSONURL="https://change.me.example.invalid/updates.json"
# A URL for the "homepage" for this mod, displayed in the mod UI
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
# A file name (in the root of the mod JAR) containing a logo for display
logoFile="aelven_expansion.png"
credits="AnonymousVoid wrote the code, worked with models, structures, mechanics, and refined the world building and ideas. SamIr0n provided all the textures, did most of the models, Built the beautiful structures, helped with writing some code, and helped with concepts. MandMLOL provided the music for the Valors Quest music disc. DarkCode404 provided the models for the Gnome entity. Kaupenjoe's youtube tutorials and discord community were very helpful in learning about new areas of modding and bugfixing."
authors="AnonymousVoid and SamIr0n, with honorable mentions to MandMLOL, DarkCode404, and many friends"
# Display Test controls the display for your mod in the server connection screen
# MATCH_VERSION means that your mod will cause a red X if the versions on client and server differ. This is the default behaviour and should be what you choose if you have server and client elements to your mod.
# IGNORE_SERVER_VERSION means that your mod will not cause a red X if it's present on the server but not on the client. This is what you should use if you're a server only mod.
# IGNORE_ALL_VERSION means that your mod will not cause a red X if it's present on the client or the server. This is a special case and should only be used if your mod has no server component.
# NONE means that no display test is set on your mod. You need to do this yourself, see IExtensionPoint.DisplayTest for more information. You can define any scheme you wish with this value.
# IMPORTANT NOTE: this is NOT an instruction as to which environments (CLIENT or DEDICATED SERVER) your mod loads on. Your mod should load (and maybe do nothing!) whereever it finds itself.
#displayTest="MATCH_VERSION" # MATCH_VERSION is the default if nothing is specified

#mandatory
description='''
This mod is still being developed.
Aelven Expansion is about magical creatures, places, and resources.
'''
# Minecraft Forge
[[dependencies.aelven_expansion]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[43,)" #mandatory
    ordering="NONE"
    side="BOTH"
# Minecraft
[[dependencies.aelven_expansion]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
# JEI
[[dependencies.aelven_expansion]]
    modId="jei"
    mandatory=false
    versionRange="[11.4.0.274]"
    ordering="NONE"
    side="CLIENT"
